package org.singapore.ghru.vo

enum class Measurements {
    SPIROMETRY,
    BLOOD_GLUCOSE,
    H_OGTT,
    TOTAL_CHOLESTEROL,
    TRIGLYCERIDES,
    HDL,
    FUNDOSCOPY,
    HB1AC,
    HIP_AND_WAIST,
    BLOOD_PRESSURE,
    BODY_COMPOSITION,
    HEIGHT,
    ECG,
    CANCEL,
    SAMPLE,
    AXIVITY,
    Enumaration,
    REGISTRATION,
    HEMOGLOBIN,
    grip_strength,
    hip,
    waist,
    DXA,
    ULTRASOUND,
    weight,
    VISUAL_ACUITY,
    TREADMILL,
    height_and_weight,
    Vicorder,
    Skin,
    Octa
}